model_lang: de
test_lang: de
model_dirs:
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/de_0_1
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/de_0_2
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/de_0_3
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/de_0_4
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/de_0_5