model_lang: zh
test_lang: zh
model_dirs:
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/zh_0_1
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/zh_0_2
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/zh_0_3
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/zh_0_4
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/zh_0_5