model_lang: en
test_lang: en
model_dirs:
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/en_0_1
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/en_0_2
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/en_0_3
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/en_0_4
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/en_0_5