model_lang: es
test_lang: es
model_dirs:
  - /home/s1948359/multilingual_sentiment_analysis/models/baseline_models/es_0_1
  - /home/s1948359/multilingual_sentiment_analysis/models/baseline_models/es_0_2
  - /home/s1948359/multilingual_sentiment_analysis/models/baseline_models/es_0_3
  - /home/s1948359/multilingual_sentiment_analysis/models/baseline_models/es_0_4
  - /home/s1948359/multilingual_sentiment_analysis/models/baseline_models/es_0_5