model_lang: en
test_lang: en
model_dirs:
  - /home/ec2-user/SageMaker/efs/sgt/models/en_15.0_0_2021_11_29_17_30_21
  - /home/ec2-user/SageMaker/efs/sgt/models/en_15.0_26_2021_11_30_09_32_18
  - /home/ec2-user/SageMaker/efs/sgt/models/en_15.0_42_2021_11_30_17_30_53
  - /home/ec2-user/SageMaker/efs/sgt/models/en_15.0_5_2021_11_30_01_31_50
  - /home/ec2-user/SageMaker/efs/sgt/models/en_15.0_63_2021_12_01_01_35_25
