model_lang: multi
test_lang: zh
model_dirs:
  - /home/s1948359/multilingual_sentiment_analysis/models/multi+en_6.0_5_2021_10_23_20_21_29
  - /home/s1948359/multilingual_sentiment_analysis/models/multi+en_6.0_42_2021_10_21_14_19_12
  - /home/s1948359/multilingual_sentiment_analysis/models/multi+en_6.0_26_2021_10_26_01_59_56
  - /home/s1948359/multilingual_sentiment_analysis/models/multi+en_6.0_0_2021_10_27_20_20_08
  - /home/s1948359/multilingual_sentiment_analysis/models/multi+en_6.0_63_2021_10_25_14_47_53
