model_lang: en
test_lang: en
model_dirs:
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/en_0_1
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/en_0_2
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/en_0_3
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/en_0_4
  - /home/ec2-user/SageMaker/efs/sgt/baseline_models/en_0_5