model_lang: de
test_lang: de
model_dirs:
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/de_0_1
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/de_0_2
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/de_0_3
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/de_0_4
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/de_0_5