model_lang: ja
test_lang: ja
model_dirs:
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/ja_0_1
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/ja_0_2
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/ja_0_3
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/ja_0_4
  - /home/s1948359/multilingual_sentiment_analysis/baseline_models/ja_0_5