models:
    en: "bert-base-cased"
    de: "bert-base-german-cased"
    ja: "cl-tohoku/bert-base-japanese"
    es: "dccuchile/bert-base-spanish-wwm-cased"
    fr: "camembert/camembert-large" # many options https://huggingface.co/camembert-base
    zh: "hfl/chinese-bert-wwm-ext"
    multi: "bert-base-multilingual-cased" # also xlm-roberta-large

compressed_models:
    en: "distilbert-base-cased"
    de: "distilbert-base-german-cased"
    ja: "bandainamco-mirai/distilbert-base-japanese"
    es: "" # couldn't find on huggingface
    zh: "ckiplab/albert-base-chinese"
    multi: "distilbert-base-multilingual-cased"

fine_tuned_models:
    en: "models/mono_en"
    de: "models/de_3_42/checkpoint-50001"  #"models/de/checkpoint-16667" "models/de_12.0_2021_08_27_12_26_30/checkpoint-200004" #"models/mono_de"
    ja: "models/mono_ja"
    es: "models/mono_es"
    multi: "models/multi"